### ISSUE TITLE
Wrong title look

### ISSUE THREAD

**Issue by himurovich** [modxcms/Collections#279] opened 2019-05-24 07:27 UTC
If I change page type to "Collection" something happens with caption style.
Please see attached screenshots.

![2019-05-24 10 22 57](https://user-images.githubusercontent.com/2815640/58310105-7d662980-7e0e-11e9-96d4-46e2a4feafee.png)

![2019-05-24 10 23 42](https://user-images.githubusercontent.com/2815640/58310104-7d662980-7e0e-11e9-95da-03461741b295.png)

MODX 2.7.1

**Comment by theboxer** [comment] 2019-05-24 08:00
Duplicate of #273

**Closed by theboxer** 2019-05-24 08:00 UTC
