### ISSUE TITLE
Error while directly editing fields in a table

### ISSUE THREAD

**Issue by rpadesign** [modxcms/Collections#303] opened 2019-10-03 09:34 UTC
After upgrading to 3.7.0-pl, data (textfield, numberfield, etc.) ceased to be saved. In console error:
![](https://i.postimg.cc/PxQHcbn2/image.png)

**Comment by theboxer** [comment] 2019-10-15 08:56
Duplicate of #297

**Closed by theboxer** 2019-10-15 08:56 UTC
