### ISSUE TITLE
Listing pagination: when updating resource always getting back to first page listing

### ISSUE THREAD

**Issue by manuel-bizen** [modxcms/Collections#282] opened 2019-07-05 08:46 UTC
i found out this quite annoying issue when updating a resource on the 2nd/3td collection container page, after saving it and going back to collection, it always takes me back to the first page. Does anybody else noticed this issue? Thanks

**Comment by theboxer** [comment] 2019-08-18 08:09
I believe this is a duplicate of #267 and will be fixed in next release.

**Closed by theboxer** 2019-08-18 08:09 UTC
